# You might have to change these.
OCAMLC=ocamlc
OCAMLOPT=ocamlopt
OCAMLMKLIB=ocamlmklib
OCAMLLIB=`$(OCAMLC) -where`
CINCLUDES=-I$(OCAMLLIB) -I/usr/include 
CC=gcc

# If you don't have libjpeg, remove the -DHAVE_JPEG and -cclib -ljpeg parts of
# the following lines.
CFLAGS=$(CINCLUDES) -DHAVE_JPEG -W -Wall -Wno-unused
LIBS=-lgd -lpng -lz -ljpeg
OCAMLCFLAGS=-labels -unsafe
OCAMLOPTFLAGS=-inline 1

OPT_FILES=gd.cmxa
INSTALL_FILES=gd.cmi gd.cma libocamlgd.a dllocamlgd.so

.PHONY : all opt install install-opt clean realclean

all: gd.cma gdtest

opt: gd.cmxa gdtest.opt


install: all
	cp -f $(INSTALL_FILES) $(OCAMLLIB)

install-opt: all
	cp -f gd.cmxa libocamlgd.a $(OCAMLLIB)

gd.cma: gd.cmi gd.cmo gdstubs.o
	ocamlmklib -o gd gd.cmo gdstubs.o -oc ocamlgd $(LIBS)

gd.cmxa: gd.cmi gd.cmx gdstubs.o
	ocamlmklib -o gd gd.cmx gdstubs.o -oc ocamlgd $(LIBS)

gd.cmx: gd.cmi gd.ml
	$(OCAMLOPT) $(OCAMLCFLAGS) -c gd.ml

gd.cmo: gd.cmi gd.ml
	$(OCAMLC) $(OCAMLCFLAGS) -c gd.ml

gd.cmi: gd.mli
	$(OCAMLC) $(OCAMLCFLAGS) -c gd.mli

gdtest: gd.cma gdtest.cmo
	$(OCAMLC) -o gdtest -dllpath . gd.cma gdtest.cmo 

gdtest.opt: gd.cmxa gdtest.ml
	$(OCAMLOPT) $(OCAMLCFLAGS) -o gdtest.opt gd.cmxa gdtest.ml

gdstubs.o: gdstubs.c
	$(CC) $(CFLAGS) -c gdstubs.c

gdtest.cmo: gd.cmi gdtest.ml
	$(OCAMLC) $(OCAMLCFLAGS) -c gdtest.ml

clean :
	-rm -f *.cmi *.cmo *.cmx *.o

realclean : clean
	-rm -f *.a *.so *.cma *.cmxa
